[project]
name = 'Traditional-Ecological-Knowledge-Documentation-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.builder-certification]
path = 'contracts/builder-certification.clar'
clarity_version = 2
epoch = 2.5

[contracts.design-registration]
path = 'contracts/design-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.material-sourcing]
path = 'contracts/material-sourcing.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
